name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build_and_push_container:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: isbang/compose-action@v1.5.1
        with:
          compose-file: "./compose.yaml"
        env:
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
