name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build_and_push_container:
    runs-on: ubuntu-latest

    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v3"

      - name: "Google auth"
        id: "auth"
        uses: "google-github-actions/auth@v1"
        with:
          workload_identity_provider: "${{ secrets.WIF_PROVIDER }}"
          service_account: "${{ secrets.WIF_SERVICE_ACCOUNT }}"

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v2"
        with:
          project_id: "dynamic-circle-417519"

      - name: "Docker auth"
        run: |-
          gcloud auth configure-docker ${{ secrets.GAR_LOCATION }}-docker.pkg.dev

      - name: Clean Docker cache
        run: docker run --rm --privileged multiarch/qemu-user-static --reset -p yes

      - name: Build the Docker image
        run: docker build --platform linux/arm64 --tag ${{ secrets.GAR_LOCATION }}-docker.pkg.dev/${{ secrets.PROJECT_ID }}/${{ secrets.APP }}/${{ secrets.APP }}:${{ github.sha }} .

      - name: Push Docker Image to repo
        run: docker push ${{ secrets.GAR_LOCATION }}-docker.pkg.dev/${{ secrets.PROJECT_ID }}/${{ secrets.APP }}/${{ secrets.APP }}:${{ github.sha }}
